services:
  api:
    build:
      context: .
      target: development # Targets the development stage in our Dockerfile
    container_name: merge_backend_api
    volumes:
      - .:/user/src/app
      - /usr/src/app/node_modules
    ports:
      - "3000:3000"
    command: npm run start:dev # Runs the live-reloading Nest server
    environment:
      - PORT=3000
      - NODE_ENV=development
      - REDIS_URL=redis://redis:6379
    depends_on:
      - redis

  redis: 
    image: redis:7-alpine
    container_name: merge_redis
    ports: 
      - "6379:6379"
    restart: unless-stopped

  biometric-worker:
    build:
      context: ./src/modules/users/infrastructure/services/biometric-worker
    container_name: merge-biometric-worker
    ports: 
      - "8000:8000"
    volumes: 
      # Mounts a local cache so the container doesn't re-download
      # the 100MB FaceNet weights every time you restart Docker.
      - ~/.deepface/weights:/root/.deepface/weights
    restart: unless-stopped


      