export const PRONOUN_SUGGESTIONS: string[] = [
  'He/Him',
  'She/Her',
  'They/Them',
  'He/They',
  'She/They',
  'Ze/Zir',
  'Any Pronouns',
  'Prefer Not to Say',
];

export const GENDER_IDENTITY_OPTIONS: string[] = [
  'Cisgender Man',
  'Cisgender Woman',
  'Transgender Man',
  'Transgender Woman',
  'Non-Binary',
  'Genderqueer',
  'Genderfluid',
  'Agender',
  'Two-Spirit',
  'Questioning',
];

export const LANGUAGE_SUGGESTIONS: string[] = [
  'English',
  'Malayalam',
  'Hindi',
  'Tamil',
  'Telugu',
  'Kannada',
  'Bengali',
  'Marathi',
  'Gujarati',
  'Punjabi',
  'Urdu',
  'Arabic',
  'French',
  'Spanish',
  'German',
];

export const INDIAN_LOCATION_DATA: Record<string, string[]> = {
  'Andhra Pradesh': [
    'Visakhapatnam',
    'Vijayawada',
    'Guntur',
    'Nellore',
    'Kurnool',
    'Rajahmundry',
    'Tirupati',
    'Kakinada',
    'Kadapa',
    'Anantapur',
    'Eluru',
    'Vizianagaram',
    'Ongole',
    'Nandyal',
    'Machilipatnam',
  ],
  'Arunachal Pradesh': [
    'Itanagar',
    'Naharlagun',
    'Pasighat',
    'Namsai',
    'Tawang',
    'Ziro',
    'Along',
    'Bomdila',
    'Roing',
    'Tezu',
  ],
  Assam: [
    'Guwahati',
    'Silchar',
    'Dibrugarh',
    'Jorhat',
    'Nagaon',
    'Tinsukia',
    'Tezpur',
    'Bongaigaon',
    'Karimganj',
    'Sivasagar',
    'Goalpara',
    'Barpeta',
    'Dhubri',
  ],
  Bihar: [
    'Patna',
    'Gaya',
    'Bhagalpur',
    'Muzaffarpur',
    'Purnia',
    'Darbhanga',
    'Bihar Sharif',
    'Arrah',
    'Begusarai',
    'Katihar',
    'Munger',
    'Chhapra',
    'Saharsa',
    'Sasaram',
    'Hajipur',
    'Dehri',
    'Siwan',
    'Motihari',
  ],
  Chhattisgarh: [
    'Raipur',
    'Bhilai',
    'Bilaspur',
    'Korba',
    'Rajnandgaon',
    'Durg',
    'Jagdalpur',
    'Ambikapur',
    'Raigarh',
    'Dhamtari',
    'Mahasamund',
  ],
  Goa: [
    'Panaji',
    'Margao',
    'Vasco da Gama',
    'Mapusa',
    'Ponda',
    'Bicholim',
    'Curchorem',
    'Cuncolim',
  ],
  Gujarat: [
    'Ahmedabad',
    'Surat',
    'Vadodara',
    'Rajkot',
    'Bhavnagar',
    'Jamnagar',
    'Junagadh',
    'Gandhinagar',
    'Anand',
    'Navsari',
    'Morbi',
    'Nadiad',
    'Surendranagar',
    'Bharuch',
    'Mehsana',
    'Bhuj',
    'Porbandar',
    'Valsad',
    'Vapi',
  ],
  Haryana: [
    'Gurugram',
    'Faridabad',
    'Panipat',
    'Ambala',
    'Yamunanagar',
    'Rohtak',
    'Hisar',
    'Karnal',
    'Sonipat',
    'Panchkula',
    'Bhiwani',
    'Sirsa',
    'Bahadurgarh',
    'Jind',
    'Thanesar',
    'Kaithal',
    'Rewari',
  ],
  'Himachal Pradesh': [
    'Shimla',
    'Dharamshala',
    'Mandi',
    'Solan',
    'Kullu',
    'Manali',
    'Baddi',
    'Nahan',
    'Hamirpur',
    'Una',
    'Bilaspur',
    'Chamba',
  ],
  Jharkhand: [
    'Ranchi',
    'Jamshedpur',
    'Dhanbad',
    'Bokaro Steel City',
    'Deoghar',
    'Phusro',
    'Hazaribagh',
    'Giridih',
    'Ramgarh',
    'Medininagar',
    'Chirkunda',
    'Chaibasa',
  ],
  Karnataka: [
    'Bengaluru',
    'Mysuru',
    'Hubballi-Dharwad',
    'Mangaluru',
    'Belagavi',
    'Kalaburagi',
    'Davanagere',
    'Ballari',
    'Vijayapura',
    'Shivamogga',
    'Tumakuru',
    'Raichur',
    'Bidar',
    'Hosapete',
    'Gadag-Betageri',
    'Udupi',
    'Hassan',
    'Bhadravati',
    'Chitradurga',
    'Kolar',
    'Mandya',
    'Chikkamagaluru',
  ],
  Kerala: [
    'Thiruvananthapuram',
    'Kochi',
    'Kozhikode',
    'Kollam',
    'Thrissur',
    'Kannur',
    'Alappuzha',
    'Kottayam',
    'Palakkad',
    'Manjeri',
    'Malappuram',
    'Thalassery',
    'Ponnani',
    'Vatakara',
    'Kanhangad',
    'Payyanur',
    'Kasaragod',
    'Koyilandy',
    'Neyyattinkara',
    'Kayamkulam',
    'Nedumangad',
    'Guruvayur',
    'Tirur',
    'Changanassery',
    'Punalur',
    'Nilambur',
    'Cherthala',
    'Perinthalmanna',
    'Mattannur',
    'Pathanamthitta',
    'Koduvally',
    'Thodupuzha',
    'Kalpetta',
  ],
  'Madhya Pradesh': [
    'Indore',
    'Bhopal',
    'Jabalpur',
    'Gwalior',
    'Ujjain',
    'Sagar',
    'Dewas',
    'Satna',
    'Ratlam',
    'Rewa',
    'Murwara (Katni)',
    'Singrauli',
    'Burhanpur',
    'Khandwa',
    'Bhind',
    'Chhindwara',
    'Guna',
    'Shivpuri',
    'Vidisha',
    'Damoh',
    'Mandsaur',
    'Khargone',
    'Neemuch',
    'Pithampur',
    'Hoshangabad',
  ],
  Maharashtra: [
    'Mumbai',
    'Pune',
    'Nagpur',
    'Thane',
    'Pimpri-Chinchwad',
    'Nashik',
    'Kalyan-Dombivli',
    'Vasai-Virar',
    'Aurangabad (Chhatrapati Sambhajinagar)',
    'Navi Mumbai',
    'Solapur',
    'Mira-Bhayandar',
    'Bhiwandi',
    'Amravati',
    'Nanded',
    'Kolhapur',
    'Ulhasnagar',
    'Sangli',
    'Malegaon',
    'Jalgaon',
    'Akola',
    'Latur',
    'Dhule',
    'Ahmednagar',
    'Chandrapur',
    'Parbhani',
    'Ichalkaranji',
    'Jalna',
    'Ambarnath',
    'Bhusawal',
    'Panvel',
    'Badlapur',
    'Beed',
    'Gondia',
    'Satara',
    'Barshi',
    'Yavatmal',
    'Achalpur',
    'Osmanabad (Dharashiv)',
    'Nandurbar',
    'Wardha',
    'Udgir',
    'Hinganghat',
  ],
  Manipur: [
    'Imphal',
    'Thoubal',
    'Bishnupur',
    'Churachandpur',
    'Kakching',
    'Ukhrul',
    'Senapati',
    'Tamenglong',
    'Jiribam',
  ],
  Meghalaya: [
    'Shillong',
    'Tura',
    'Nongpoh',
    'Jowai',
    'Baghmara',
    'Williamnagar',
    'Resubelpara',
    'Mairang',
    'Nongstoin',
  ],
  Mizoram: [
    'Aizawl',
    'Lunglei',
    'Champhai',
    'Serchhip',
    'Kolasib',
    'Lawngtlai',
    'Saitual',
    'Khawzawl',
    'Mamit',
  ],
  Nagaland: [
    'Dimapur',
    'Kohima',
    'Mokokchung',
    'Tuensang',
    'Wokha',
    'Zunheboto',
    'Mon',
    'Phek',
    'Chumoukedima',
  ],
  Odisha: [
    'Bhubaneswar',
    'Cuttack',
    'Rourkela',
    'Berhampur',
    'Sambalpur',
    'Puri',
    'Balasore',
    'Bhadrak',
    'Baripada',
    'Jharsuguda',
    'Jeypore',
    'Bargarh',
    'Rayagada',
    'Bolangir',
    'Angul',
    'Dhenkanal',
  ],
  Punjab: [
    'Ludhiana',
    'Amritsar',
    'Jalandhar',
    'Patiala',
    'Bathinda',
    'Hoshiarpur',
    'Mohali (SAS Nagar)',
    'Batala',
    'Pathankot',
    'Moga',
    'Abohar',
    'Malerkotla',
    'Khanna',
    'Phagwara',
    'Muktsar',
    'Barnala',
    'Firozpur',
    'Kapurthala',
  ],
  Rajasthan: [
    'Jaipur',
    'Jodhpur',
    'Kota',
    'Bikaner',
    'Ajmer',
    'Udaipur',
    'Bhilwara',
    'Alwar',
    'Bharatpur',
    'Sikar',
    'Pali',
    'Sri Ganganagar',
    'Kishangarh',
    'Baran',
    'Dhaulpur',
    'Tonk',
    'Beawar',
    'Hanumangarh',
  ],
  Sikkim: [
    'Gangtok',
    'Namchi',
    'Gyalshing',
    'Mangan',
    'Rangpo',
    'Singtam',
    'Jorethang',
    'Ravangla',
  ],
  'Tamil Nadu': [
    'Chennai',
    'Coimbatore',
    'Madurai',
    'Tiruchirappalli',
    'Salem',
    'Tiruppur',
    'Erode',
    'Vellore',
    'Thoothukudi',
    'Dindigul',
    'Thanjavur',
    'Ranipet',
    'Sivakasi',
    'Karur',
    'Udhagamandalam (Ooty)',
    'Hosur',
    'Nagercoil',
    'Kanchipuram',
    'Kumarapalayam',
    'Karaikkudi',
    'Neyveli',
    'Cuddalore',
    'Kumbakonam',
    'Tiruvannamalai',
    'Pollachi',
    'Rajapalayam',
    'Gudiyatham',
    'Pudukkottai',
  ],
  Telangana: [
    'Hyderabad',
    'Warangal',
    'Nizamabad',
    'Khammam',
    'Karimnagar',
    'Ramagundam',
    'Mahbubnagar',
    'Nalgonda',
    'Adilabad',
    'Suryapet',
    'Miryalaguda',
    'Siddipet',
    'Jagtial',
    'Mancherial',
  ],
  Tripura: [
    'Agartala',
    'Dharmanagar',
    'Udaipur',
    'Kailashahar',
    'Bishalgarh',
    'Teliamura',
    'Khowai',
    'Belonia',
    'Melaghar',
    'Ambassa',
  ],
  'Uttar Pradesh': [
    'Lucknow',
    'Kanpur',
    'Ghaziabad',
    'Agra',
    'Meerut',
    'Varanasi',
    'Prayagraj (Allahabad)',
    'Bareilly',
    'Aligarh',
    'Moradabad',
    'Saharanpur',
    'Gorakhpur',
    'Noida',
    'Firozabad',
    'Jhansi',
    'Muzaffarnagar',
    'Mathura',
    'Budaun',
    'Rampur',
    'Shahjahanpur',
    'Farrukhabad',
    'Ayodhya',
    'Hapur',
    'Etawah',
    'Mirzapur',
    'Bulandshahr',
    'Sambhal',
    'Amroha',
    'Hardoi',
    'Fatehpur',
    'Raebareli',
    'Orai',
    'Sitapur',
    'Bahraich',
    'Modinagar',
    'Unnao',
    'Jaunpur',
  ],
  Uttarakhand: [
    'Dehradun',
    'Haridwar',
    'Roorkee',
    'Haldwani',
    'Rudrapur',
    'Kashipur',
    'Rishikesh',
    'Pithoragarh',
    'Ramnagar',
    'Manglaur',
    'Nainital',
    'Mussoorie',
    'Almora',
  ],
  'West Bengal': [
    'Kolkata',
    'Howrah',
    'Asansol',
    'Siliguri',
    'Durgapur',
    'Bardhaman',
    'Malda',
    'Baharampur',
    'Habra',
    'Kharagpur',
    'Shantipur',
    'Dankuni',
    'Dhulian',
    'Ranaghat',
    'Haldia',
    'Raiganj',
    'Krishnanagar',
    'Nabadwip',
    'Midnapore',
    'Jalpaiguri',
    'Balurghat',
    'Basirhat',
    'Bankura',
    'Darjeeling',
    'Alipurduar',
    'Purulia',
  ],
  'Andaman and Nicobar Islands': [
    'Port Blair',
    'Garacharma',
    'Bambooflat',
    'Diglipur',
    'Rangat',
    'Mayabunder',
  ],
  Chandigarh: ['Chandigarh'],
  'Dadra and Nagar Haveli and Daman and Diu': [
    'Daman',
    'Diu',
    'Silvassa',
    'Amli',
  ],
  Delhi: [
    'New Delhi',
    'Central Delhi',
    'North Delhi',
    'South Delhi',
    'East Delhi',
    'West Delhi',
    'North East Delhi',
    'North West Delhi',
    'South East Delhi',
    'South West Delhi',
    'Shahdara',
  ],
  'Jammu and Kashmir': [
    'Srinagar',
    'Jammu',
    'Anantnag',
    'Baramulla',
    'Kathua',
    'Sopore',
    'Udhampur',
    'Poonch',
    'Rajouri',
    'Kupwara',
    'Pulwama',
  ],
  Ladakh: ['Leh', 'Kargil'],
  Lakshadweep: ['Kavaratti', 'Agatti', 'Amini', 'Andrott', 'Minicoy'],
  Puducherry: ['Puducherry', 'Karaikal', 'Mahe', 'Yanam'],
};