export const API_ENDPOINTS = {
    AUTH: {
        BASE: '/auth',
        LOGIN: '/auth/login',
        REGISTER: '/auth/register',
        VERIFY_OTP: '/auth/verify-otp',
        RESEND_OTP: '/auth/resend-otp',
        REFRESH: '/auth/refresh',
        LOGOUT: '/auth/logout',
        GOOGLE: '/auth/google',
        FORGOT_PASSWORD: '/auth/forgot-password',
        RESET_PASSWORD: '/auth/reset-password',
    },
    KYC: {
        BASE: '/kyc',
        SUBMIT: '/kyc/submit',
        SELFIE: '/kyc/selfie',
        LIVENESS: '/kyc/liveness',
        SUBMIT_VERIFICATION: '/kyc/submit-verification',
    },
    HANDOFF: {
        BASE: '/verification/phone-handoff',
        SESSION: '/verification/phone-handoff/session',
        CANCEL: (sessionId: string) => `/verification/phone-handoff/${sessionId}/cancel`,
        VALIDATE: (sessionId: string) => `/verification/phone-handoff/${sessionId}`,
        COMPLETE: (sessionId: string) => `/verification/phone-handoff/${sessionId}/complete`,
    },
    PROFILE: {
        BASE: '/profile',
        FULL: '/profile/full',
        PHOTOS: '/profile/photos',
        PHOTOS_PRIMARY: '/profile/photos/primary',
        PHOTO_BY_ID: (photoId: string) => `/profile/photos/${photoId}`,
        MEDICAL: '/profile/medical',
        PREFERENCES: '/profile/preferences',
        PRIVACY: '/profile/privacy',
        PERSONA: '/profile/persona',
        LIFESTYLE: '/profile/lifestyle',
        BIO_GENERATE: '/profile/bio/generate',
        BIO_SAVE: '/profile/bio/save',
        SECURITY_OTP_REQUEST: '/profile/security/otp/request',
        SECURITY_PASSWORD: '/profile/security/password',
        SECURITY_EMAIL_INITIATE: '/profile/security/email/initiate',
        SECURITY_EMAIL_CONFIRM: '/profile/security/email/confirm',
        SECURITY_ACCOUNT_DEACTIVATE: '/profile/security/account/deactivate',
        SECURITY_ACCOUNT_DELETE: '/profile/security/account/delete',
        SECURITY_SESSIONS: '/profile/security/sessions',
        SECURITY_SESSIONS_REVOKE: (sessionId: string) => `/profile/security/sessions/${sessionId}`,
        SECURITY_SESSIONS_OTHER: '/profile/security/sessions/other',
        BLOCKED: '/profile/blocked',
        BLOCKED_BY_ID: (blockedId: string) => `/profile/blocked/${blockedId}`,
    },
    CASTING_DIRECTOR: {
        BASE: '/casting-director',
        INITIALIZE: '/casting-director/initialize',
        MESSAGE: '/casting-director/message',
        FINALIZE: '/casting-director/finalize',
    },
    ADMIN: {
        AUTH: {
            BASE: '/admin/auth',
            LOGIN: '/admin/auth/login',
            REFRESH: '/admin/auth/refresh',
            LOGOUT: '/admin/auth/logout',
            FORGOT_PASSWORD: '/admin/auth/forgot-password',
            VERIFY_RESET_OTP: '/admin/auth/verify-reset-otp',
            RESET_PASSWORD: '/admin/auth/reset-password',
        },
        USERS: {
            BASE: '/admin/users',
            BY_ID: (id: string) => `/admin/users/${id}`,
            SUSPEND: (id: string) => `/admin/users/${id}/suspend`,
            UNSUSPEND: (id: string) => `/admin/users/${id}/unsuspend`,
            BAN: (id: string) => `/admin/users/${id}/ban`,
            UNBAN: (id: string) => `/admin/users/${id}/unban`,
        },
        MANAGEMENT: {
            BASE: '/admin/management',
            BY_ID: (id: string) => `/admin/management/${id}`,
            INVITE: '/admin/management/invite',
            ACCEPT_INVITE: '/admin/management/accept-invite',
            REINVITE: (id: string) => `/admin/management/${id}/reinvite`,
            CANCEL_INVITE: (id: string) => `/admin/management/${id}/cancel-invite`,
            SUSPEND: (id: string) => `/admin/management/${id}/suspend`,
            DEACTIVATE: (id: string) => `/admin/management/${id}/deactivate`,
            REACTIVATE: (id: string) => `/admin/management/${id}/reactivate`,
            FORCE_LOGOUT: (id: string) => `/admin/management/${id}/force-logout`,
        },
        PHOTO_VERIFICATION: {
            BASE: '/admin/photo-verification',
            CLAIM: (id: string) => `/admin/photo-verification/${id}/claim`,
            RELEASE: (id: string) => `/admin/photo-verification/${id}/release`,
            TAKEOVER: (id: string) => `/admin/photo-verification/${id}/takeover`,
            APPROVE: (id: string) => `/admin/photo-verification/${id}/approve`,
            REJECT: (id: string) => `/admin/photo-verification/${id}/reject`,
        }
    }
} as const;