export const ErrorCode = {
    // Auth & Identity
    USER_NOT_FOUND: 'USER_NOT_FOUND',
    USER_ALREADY_EXISTS: 'USER_ALREADY_EXISTS',
    USER_SUSPENDED: 'USER_SUSPENDED',
    INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
    EMAIL_NOT_VERIFIED: 'EMAIL_NOT_VERIFIED',
    OTP_EXPIRED: 'OTP_EXPIRED',
    OTP_INVALID: 'OTP_INVALID',
    TOKEN_EXPIRED: 'TOKEN_EXPIRED',
    TOKEN_INVALID: 'TOKEN_INVALID',
    UNAUTHORIZED: 'UNAUTHORIZED',
    FORBIDDEN: 'FORBIDDEN',

    // KYC & Biometrics
    KYC_DOCUMENT_INVALID: 'KYC_DOCUMENT_INVALID',
    KYC_ALREADY_SUBMITTED: 'KYC_ALREADY_SUBMITTED',
    KYC_ALREADY_VERIFIED: 'KYC_ALREADY_VERIFIED',
    DUPLICATE_KYC_DOCUMENT: 'DUPLICATE_KYC_DOCUMENT',
    LIVENESS_CHECK_FAILED: 'LIVENESS_CHECK_FAILED',
    FACE_MISMATCH: 'FACE_MISMATCH',
    AADHAAR_VERIFICATION_FAILED: 'AADHAAR_VERIFICATION_FAILED',

    // AI & Profile Generation
    AI_SERVICE_UNAVAILABLE: 'AI_SERVICE_UNAVAILABLE',
    BIO_GENERATION_FAILED: 'BIO_GENERATION_FAILED',

    // Infrastructure & Storage
    FILE_UPLOAD_FAILED: 'FILE_UPLOAD_FAILED',
    RESOURCE_NOT_FOUND: 'RESOURCE_NOT_FOUND',

    // Handoff (QR Code WebSocket)
    HANDOFF_SESSION_EXPIRED: 'HANDOFF_SESSION_EXPIRED',
    HANDOFF_SESSION_INVALID: 'HANDOFF_SESSION_INVALID',

    // General
    INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',
    VALIDATION_FAILED: 'VALIDATION_FAILED',
} as const;

// Derive the TypeScript union type
export type ErrorCode = (typeof ErrorCode)[keyof typeof ErrorCode];