export const ErrorCode = {
    // Auth & Identity
    USER_NOT_FOUND: 'USER_NOT_FOUND',
    USER_ALREADY_EXISTS: 'USER_ALREADY_EXISTS',
    INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
    EMAIL_NOT_VERIFIED: 'EMAIL_NOT_VERIFIED',
    OTP_EXPIRED: 'OTP_EXPIRED',
    OTP_INVALID: 'OTP_INVALID',
    TOKEN_EXPIRED: 'TOKEN_EXPIRED',
    TOKEN_INVALID: 'TOKEN_INVALID',

    // KYC & Biometrics
    KYC_DOCUMENT_INVALID: 'KYC_DOCUMENT_INVALID',
    LIVENESS_CHECK_FAILED: 'LIVENESS_CHECK_FAILED',
    FACE_MISMATCH: 'FACE_MISMATCH',
    AADHAAR_VERIFICATION_FAILED: 'AADHAAR_VERIFICATION_FAILED',

    // Handoff (QR Code WebSocket)
    HANDOFF_SESSION_EXPIRED: 'HANDOFF_SESSION_EXPIRED',
    HANDOFF_SESSION_INVALID: 'HANDOFF_SESSION_INVALID',

    // General
    INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',
    VALIDATION_FAILED: 'VALIDATION_FAILED',
} as const;

// Derive the TypeScript union type
export type ErrorCode = (typeof ErrorCode)[keyof typeof ErrorCode];