export const API_ENDPOINTS = {
    AUTH: {
        BASE: 'auth',
        LOGIN: 'login',
        REGISTER: 'register',
        VERIFY_OTP: 'verify-otp',
        RESEND_OTP: 'resend-otp',
        REFRESH: 'refresh',
        LOGOUT: 'logout',
        GOOGLE: 'google',
        FORGOT_PASSWORD: 'forgot-password',
        RESET_PASSWORD: 'reset-password',
    },
    KYC: {
        BASE: 'kyc',
        SUBMIT: 'submit',
        SELFIE: 'selfie',
        LIVENESS: 'liveness',
        SUBMIT_VERIFICATION: 'submit-verification',
    },
    HANDOFF: {
        BASE: 'verification/phone-handoff',
        SESSION: 'session',
        CANCEL: ':sessionId/cancel',
        VALIDATE: ':sessionId',
        COMPLETE: ':sessionId/complete',
    },
    PROFILE: {
        BASE: 'profile',
        FULL: 'full',
        PHOTOS: 'photos',
        PHOTOS_PRIMARY: 'photos/primary',
        PHOTO_BY_ID: 'photos/:photoId',
        MEDICAL: 'medical',
        PREFERENCES: 'preferences',
        PRIVACY: 'privacy',
        PERSONA: 'persona',
        LIFESTYLE: 'lifestyle',
        BIO_GENERATE: 'bio/generate',
        BIO_SAVE: 'bio/save',
        SECURITY_OTP_REQUEST: 'security/otp/request',
        SECURITY_PASSWORD: 'security/password',
        SECURITY_EMAIL_INITIATE: 'security/email/initiate',
        SECURITY_EMAIL_CONFIRM: 'security/email/confirm',
        SECURITY_ACCOUNT_DEACTIVATE: 'security/account/deactivate',
        SECURITY_ACCOUNT_DELETE: 'security/account/delete',
        SECURITY_SESSIONS: 'security/sessions',
        SECURITY_SESSIONS_REVOKE: 'security/sessions/:sessionId',
        SECURITY_SESSIONS_OTHER: 'security/sessions/other',
        BLOCKED: 'blocked',
        BLOCKED_BY_ID: 'blocked/:blockedId',
    },
    CASTING_DIRECTOR: {
        BASE: 'casting-director',
        INITIALIZE: 'initialize',
        MESSAGE: 'message',
        FINALIZE: 'finalize',
    },
    ADMIN: {
        AUTH: {
            BASE: 'admin/auth',
            LOGIN: 'login',
            REFRESH: 'refresh',
            LOGOUT: 'logout',
            FORGOT_PASSWORD: 'forgot-password',
            VERIFY_RESET_OTP: 'verify-reset-otp',
            RESET_PASSWORD: 'reset-password',
        },
        USERS: {
            BASE: 'admin/users',
            BY_ID: ':id',
            SUSPEND: ':id/suspend',
            UNSUSPEND: ':id/unsuspend',
            BAN: ':id/ban',
            UNBAN: ':id/unban',
        },
        MANAGEMENT: {
            BASE: 'admin/management',
            BY_ID: ':id',
            INVITE: 'invite',
            ACCEPT_INVITE: 'accept-invite',
            REINVITE: ':id/reinvite',
            CANCEL_INVITE: ':id/cancel-invite',
            SUSPEND: ':id/suspend',
            DEACTIVATE: ':id/deactivate',
            REACTIVATE: ':id/reactivate',
            FORCE_LOGOUT: ':id/force-logout',
        },
        PHOTO_VERIFICATION: {
            BASE: 'admin/photo-verification',
            CLAIM: ':id/claim',
            RELEASE: ':id/release',
            TAKEOVER: ':id/takeover',
            APPROVE: ':id/approve',
            REJECT: ':id/reject',
        }
    }
} as const;